<?php
/**
 * Ponemos la siguiente notación para el autocompletado del código 
 * @var \Hanhan\Leccion2\Block\Main $block
 */

 /**
  * Usar los siguientes métodos para los strings
  * $block->escapeHtml()
  * $block->escapeQuote()
  * $block->escapeUrl()
  * $block->escapeXssInUrl()
  * __()
  */
?>

<?php
$posts = $block->tomarPosts();
?>

<!-------------------------------------------->
<h1>Saludo</h1>

<?php
/**
 * Recuerda tenemos que ponerla variable $block en vez del $this como en magento 1
 */
echo $block->saludar();

/**
 * El helper no debe usar directamente en los templates. Se debe importar en los bloques y luego 
 * considerarlo com parte del bloque
 */
echo "<br/>";
echo "el nombre de este módulo es {$block->getNombreModulo()}";
?>

<!-------------------------------------------->
<hr/>

<?php // Recorrer todos los posts?>

<dl>
<?php foreach($posts as $post): ?>
    <dt><?php echo $post->getTitle() ?></dt>
    <dd><?php echo $post->getText() ?></dd>
<?php endforeach; ?>
</dl>

<!-------------------------------------------->
<hr/>
<h1>Rellenar el formulario y clicar submit para guardar los datos</h1>
<form 
    action="<?= $block->escapeUrl($block->getFormAction()) ?>"
    method="post">
    Titulo: <br/>
    <input type="text" name="title" />
    Texto: <br/>
    <input type="text" name="text"/>
    <br/><br/>
    <input type="submit" value="Submit"/>
</form>